services:
  node-api:
    build: ./server/
    ports:
      - 3000:${PORT}
    environment:
      - PORT=${PORT}
      - EMAIL_ACCOUNT=${EMAIL_ACCOUNT}
      - GOOGLE_APP_PASSWORD=${GOOGLE_APP_PASSWORD}
      - CLIENT_URL=${CLIENT_URL}
      - JWT_SECRET=${JWT_SECRET}
      - DATABASE_URL=${DATABASE_URL}
      - PAYSTACK_SECRET_KEY=${PAYSTACK_SECRET_KEY}
      - PAYSTACK_PUBLIC_KEY=${PAYSTACK_PUBLIC_KEY}

  react-app:
    build: ./client
    ports:
      - 9000:9000
    stdin_open: true
    tty: true
